# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 00:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredus',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
