# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0003_auto_20170716_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voters',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edus.UserEdus'), null=True, related_name='voters', to='edus.UserEdus'),
        ),
    ]
