# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0004_auto_20170716_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voters',
        ),
        migrations.AddField(
            model_name='useredus',
            name='question_votes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edus.Question'),
        ),
    ]
