# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0005_auto_20170716_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useredus',
            old_name='question_votes',
            new_name='questionvotes',
        ),
    ]
