# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edus', '0006_auto_20170717_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useredus',
            name='questionvotes',
        ),
        migrations.AddField(
            model_name='question',
            name='voters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
