# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0007_auto_20170717_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='edus.UserEdus'),
        ),
    ]
