# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0011_auto_20170717_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voters',
        ),
        migrations.AddField(
            model_name='question',
            name='voters',
            field=models.ManyToManyField(null=True, related_name='voters', to='edus.UserEdus'),
        ),
    ]
