# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0012_auto_20170717_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='voters',
            field=models.ManyToManyField(null=True, related_name='voters_reply', to='edus.UserEdus'),
        ),
    ]
