# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0013_reply_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredus',
            name='email',
            field=models.CharField(help_text='Your email', max_length=500, null=True),
        ),
    ]
