# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0015_auto_20170718_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='document',
            field=models.FileField(default=None, null=True, upload_to='MEDIA_ROOT/documents/'),
        ),
    ]
