# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0017_auto_20170718_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_ROOT/documents/'),
        ),
    ]
