# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0019_newupdatesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredus',
            name='new_replies',
            field=models.BooleanField(default=False),
        ),
    ]
