# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0020_useredus_new_replies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUpdateSign',
        ),
    ]
