# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0021_delete_newupdatesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='new_replies',
            field=models.BooleanField(default=False),
        ),
    ]
