# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edus', '0022_question_new_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredus',
            name='new_replies_value',
            field=models.IntegerField(default=0),
        ),
    ]
